[ALS-6924] Take a Tour for PIC-SURE Demo
hms-dbmi/PIC-SURE-Frontend pull request #289
Opened 2024-11-05 14:24 UTC by Gcolon021

[ALS-6924] Take a Tour for PIC-SURE Demo
[ALS-7795] Tour on Discover does not apply a filter

2024-11-05 14:50 UTC, JamesPeck requested changes

2024-11-05 14:50 UTC, JamesPeck commented on src/routes/(picsure)/(public)/discover/+page.svelte
> +  /* eslint-disable @typescript-eslint/no-explicit-any */
```suggestion
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
```

2024-11-05 14:50 UTC, JamesPeck commented on src/routes/(picsure)/(authorized)/explorer/+page.svelte
> +  /* eslint-disable @typescript-eslint/no-explicit-any */
```suggestion
  /* eslint-disable-next-line @typescript-eslint/no-explicit-any */
```

2024-11-05 14:50 UTC, JamesPeck commented on src/routes/(picsure)/(authorized)/explorer/+page.svelte
> +  const tourName: string | undefined = import.meta.env.VITE_AUTH_TOUR_NAME;
Do you mind adding this to the .env example file?

2024-11-05 14:50 UTC, JamesPeck commented on src/routes/(picsure)/(public)/discover/+page.svelte
> +  const tourName = import.meta.env.VITE_OPEN_TOUR_NAME;
Do you mind adding this to the .env example file?

2024-11-06 18:38 UTC, Gcolon021 commented
@JamesPeck I am re-running the test, but I am not hopeful.

Here are my local test passing.
![image](https://github.com/user-attachments/assets/3539f89f-a3c8-4b2a-b178-1b8f590cc43a)

2024-11-07 13:46 UTC, JamesPeck approved these changes

2024-11-07 13:47 UTC, merged